{
 "title": "Dnsd Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Dnsd Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number Of Rules",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnsd_ip_blocklist_rules_count{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocked Query by source_ip",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "avg(dnsd_source_blocked_total{}) by (source_ip) ",
     "legendFormat": "{{source_ip}}"
    }
   ]
  },
  {
   "title": "Blocked Dns Server (bypass attemption rate 5m)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "rate(dnsd_blocked_dns_servers_count{}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocked Dns Count (rate 5min)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(dnsd_blocked_domains_count{}[15m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Dns Queries (rate 5min)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(dnsd_xdp_dns_queries_total{}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "XDP Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Xdp Packets Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(dnsd_xdp_packets_total{}[15m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Xdp Allow Packet Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(dnsd_xdp_allowed_total{}[15m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}